apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql
  namespace: sonar
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
     storage: "20Gi"
  storageClassName: default